app = "discord-qr-bot"
primary_region = "sin"  # Singapore region, you can change this to your preferred region

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[processes]
  app = "python main.py" 